### ISSUE TITLE
C compiler test failed.

### ISSUE THREAD

**Issue by liangrk** [CWXVashon/FFmpegCmd#1]
hi  我是从博客中看到的过来的 
我参照你博客中的脚本尝试着修改编译ffmpeg 却始终没能如愿过编.

这是我在ubuntu上编译4.4的一个编译错误日志. 希望能得到你的帮助
```
/home/admin/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/
clang: error while loading shared libraries: 
/home/admin/android-ndk-r21e/toolchains/llvm/
    prebuilt/linux-x86_64/bin/../lib64/libc++.so.1: file too short
C compiler test failed.
```

环境: ubuntu-20.4/ NDK: android-ndk-r21e/ ffmpeg-4.4-release

**Comment by CWXVashon** [comment]
方便粘一下编译脚本吗？

**Comment by liangrk** [comment]
脚本如下: 
```
#!/bin/bash
set -x

API=21
NDK=/home/admin/android-ndk-r21e

# clang config
HOST=linux-x86_64
TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/$HOST/bin
SYSROOT=$NDK/sysroot

function build_so() {
  echo "compiling ffmpeg for $CPU"
  ./configure \
      --prefix=$PREFIX \
      --enable-shared \
      --libdir=$LIB_DIR \
      --disable-static \
      --enable-jni \
      --disable-doc \
      --disable-symver \
      --disable-programs \
      --target-os=android \
      --arch=$ARCH \
      --cpu=$CPU \
      --cc=$CC \
      --cxx=$CXX \
      --enable-cross-compile \
      --sysroot=$SYSROOT \
      --extra-cflags="-Os -fpic $OPTIMIZE_CFLAGS" \
      --extra-ldflags="$ADDI_LDFLAGS" \
      --disable-asm \
      $COMMON_FF_CFG_FLAGS
      
      make clean
      make -j4
      make install
	
      echo "complie end; output:$LIB_DIR"
}

## armv7-a
function v7() {
  source "config-env.sh"
  OUTPUT "armeabi-v7a"
  
  ARCH="arm"
  CPU="armv7-a"
  PREFIX="${PWD}/android_build/$OUTPUT"
  LIB_DIR="${PWD}/android_build/libs/$OUTPUT"

  OPTIMIZE_CFLAGS="-march=$CPU -Wl,--fix-cortex-a8"
  
  CC="$TOOLCHAIN/armv7a-linux-androideabi$API-clang"
  CXX="$TOOLCHAIN/armv7a-linux-androideabi$API-clang++"
  
  build_so	
}

v7
```

**Comment by CWXVashon** [comment]
你好，你编译选项漏了一项，你开启了跨平台编译，但是没有配置跨平台编译的前缀，这样会导致找不到某些工具的：
--enable-cross-compile
--cross-prefix=$TOOLCHAIN/$ARCH-linux-androideabi-

**Comment by CWXVashon** [comment]
追加，还有你的库与头文件路径配的有点问题
SYSROOT=$NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot

**Comment by liangrk** [comment]
收到你的回复后我尝试添加了
`--cross-prefix=$TOOLCHAIN/$ARCH-linux-androideabi-`
很遗憾没有任何效果, 我尝试到 /fbuild/config 中查看日志, 错误信息也跟上面一致  

SYSROOT 路径我这边没有找到你所说. 下面是我切换到 $NDK/toolchains/llvm/prebuilt/linux-x86_64 路径下的截图

![image](https://user-images.githubusercontent.com/39788948/128483212-0b15afb3-eded-4e1b-b7d3-ddc74c207e75.png)

**Comment by CWXVashon** [comment]
建议你去官网重新下载 NDK，我认为你的 NDK 里缺了不少东西，因为你那个目录内的库少了不少，这是我的目录截图
![1](https://user-images.githubusercontent.com/23317370/128486242-35206856-dd7e-4631-9689-86c9cc686a7e.png)
![2](https://user-images.githubusercontent.com/23317370/128486267-1d6472e8-1b0b-4fac-9624-ae3eba098423.png)

**Comment by CWXVashon** [comment]
追加，如果你之后想要把构建出多个 so 变为构建出一个 so ，可能用到 gcc 这个库，记得使用
$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a
不要使用
$NDK/toolchains/llvm/prebuilt/linux-x86_64/...
否则你会发现一直构建失败，这也是一个坑。。。

**Comment by liangrk** [comment]
我更换ndk版本后可以通过编译;
后面我完善脚本后再尝试合并多个 so 库, 感谢今天的指导及预先指出的坑位~
thx
